### PR TITLE
Use constructors during deserialization. Update deps.

### PR DESCRIPTION
**Pull request by oschwald**

### CODE REVIEW

**Comment by eilara** [comment]
Unrelated to this change, but I saw it one the way, `MinFraudException` is the base class for most of these, so they can be removed from the signature:

https://github.com/maxmind/minfraud-api-java/blob/greg/use-constructors/src/main/java/com/maxmind/minfraud/WebServiceClient.java#L187

**Comment by oschwald** [comment]
Yeah, we could although it does serve as documentation as people will likely want to catch the more specific exceptions.

**Comment by eilara** [comment]
Gotcha about the exceptions, and why is the httpStatus not recorded in this exception or its subclasses? (also not related to this change):

https://github.com/maxmind/minfraud-api-java/blob/master/src/main/java/com/maxmind/minfraud/exception/InvalidRequestException.java#L32

**Comment by eilara** [comment]
Where all the `final` modifiers removed because of the JSON serializer change?

**Comment by eilara** [comment]
Again unrelated, probably 1st time running the code analysis on this:

https://github.com/maxmind/minfraud-api-java/blob/greg/use-constructors/src/main/java/com/maxmind/minfraud/request/ShoppingCartItem.java#L86

and 

https://github.com/maxmind/minfraud-api-java/blob/greg/use-constructors/src/main/java/com/maxmind/minfraud/request/Order.java#L69

are calling doubleValue on things which are already double.

I could move these things to a new pt if you wish.

**Comment by eilara** [comment]
Noticed we usually place a class description at the top, except here:

https://github.com/maxmind/minfraud-api-java/blob/greg/use-constructors/src/test/java/com/maxmind/minfraud/request/RequestTestHelper.java#L16

**Comment by oschwald** [comment]
@eilara, the final modifiers on methods in final classes were removed because they are pointless.

**Comment by eilara** [comment]
https://github.com/maxmind/minfraud-api-java/blob/dadf0058c07149d7d7fd00835a34386cb210748a/src/test/java/com/maxmind/minfraud/WebServiceClientTest.java#L179

Can work with no exceptions in the signature, since you are just creating a client and not sending a request:

https://github.com/maxmind/minfraud-api-java/blob/dadf0058c07149d7d7fd00835a34386cb210748a/src/test/java/com/maxmind/minfraud/WebServiceClientTest.java#L179

**Comment by eilara** [comment]
Final modifiers: it does make it harder for clients to subclass, break the class contract (Java makes this very easy), and then open an issue about a bug in the MaxMind library, and it makes it explicit the API is designed so you do not subclass these, but it is sometimes very inconvenient in a library so I see your point.

**Pull request merged**
